### ISSUE TITLE
[TicTacToe] ConditionToChar

### ISSUE THREAD

**Issue by pavel-b-novikov** [DontStopMeNow/nsudotnet#1]
``` C#
Value = ConditionToChar.GetChar(value);
```

Ребята, во имя всего святого, познайте институт ValueConverter-ов и смените эту гениальную конструкцию на человеческую.

**Comment by stpospelov** [comment]
Исправления: https://github.com/DontStopMeNow/nsudotnet/commit/06e9a79f51511698891b2252998d9dd168b73560

**Comment by pavel-b-novikov** [comment]
Да что ж вы его в каждом контроле создаете-то заново, а..
В ресурсы app.xaml его перенесите, чтобы не плодить лишних экземпляров.

**Comment by stpospelov** [comment]
так? https://github.com/DontStopMeNow/nsudotnet/commit/bce2b34583f24faec98218509fd3b59144cefbf6

**Comment by pavel-b-novikov** [comment]
Да
