### ISSUE TITLE
[TicTacToe] События

### ISSUE THREAD

**Issue by pavel-b-novikov** [DontStopMeNow/nsudotnet#2]
``` XML
 <i:Interaction.Triggers>
 <i:EventTrigger EventName="Click">
  <cal:ActionMessage MethodName="Click">
  </cal:ActionMessage>
 </i:EventTrigger>
</i:Interaction.Triggers>
```

А то есть cal:Message.Attach, как я показывал, не заработал?  Сэксибойз, вы меня расстраиваете.

https://caliburnmicro.codeplex.com/wikipage?title=Cheat%20Sheet

**Comment by stpospelov** [comment]
Исправления: https://github.com/DontStopMeNow/nsudotnet/commit/045d7fc8746e80e3062c498cda340282a26cd203

**Comment by pavel-b-novikov** [comment]
Ну вот так-то лучше, да. А то вы делаете за Caliburn его работу.
