### ISSUE TITLE
[TicTacToe] Баг

### ISSUE THREAD

**Issue by pavel-b-novikov** [DontStopMeNow/nsudotnet#3]
У вас, если заметили, есть баг. Когда мышку наводишь на центр суб-поля, кнопка перестает быть активной и мышкой по ней не попадается. 

Я разобрался в чем причина за 3 минуты. Вам предлагаю сделать то же самое. Там не rocket science, баг весьма уныл и скучен, но бесит капец.

По разрешении всех Issues получите свой зачет. Задача сделана вполне себе ничотак. Вы молодцы.

**Comment by stpospelov** [comment]
Исправления: https://github.com/DontStopMeNow/nsudotnet/commit/da4bd4d067f4ea19ff19b95bdffacd06e245a7ba

**Comment by pavel-b-novikov** [comment]
![image](https://cloud.githubusercontent.com/assets/2521412/7787422/035f4362-022d-11e5-9192-f4e21c308a2f.png)
Неа

**Comment by stpospelov** [comment]
Теперь точно все работают: https://github.com/DontStopMeNow/nsudotnet/commit/a255800453fa97b3507c86ad13ba18e0ac913569 . Не заметил эту кнопку в первый раз.

**Comment by pavel-b-novikov** [comment]
Ну фикс бага странный, если честно.
Я бы добавил байндинг на Visibility через конвертер на IsWon или что-то в этом духе с условием что False = Collapsed... Но ладно.
